
GET http://localhost:3000/test

###

GET http://localhost:3000/jobs

####


GET http://localhost:3000/jobs/5

####


POST http://localhost:3000/jobs
content-type: application/json

{"jobTitle":"Test Ops 2","company":"Roncal Ltd","region":"Cardiff","jobCategory":"IT"}

###


PUT http://localhost:3000/jobs/5
content-type: application/json

{"jobTitle":"DevOps Engineer","company":"Roncal Ltd","region":"London","jobCategory":"IT"}

###

DELETE http://localhost:3000/jobs/5

####


GET http://localhost:3000/jobSearch/cyc

####
